#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: WR1200JS
      run: |
        cd /opt/rt-n56u/trunk
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config #删除配置项SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #删除配置项阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FIREFLY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' .config
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #MENTOHUST
        echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> .config #SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> .config #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> .config # simple-obfs混淆插件
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config #SS server
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config #DNSFORWARDER
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config #adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config #内网穿透FRPC
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> .config #内网穿透FRPS
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> .config #TUNSAFE
        echo "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> .config #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_FIREFLY=n" >> .config #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> .config #smartdns二进制文件
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_FTPD=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./build_firmware_modify WR1200JS
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
